#!/bin/bash
# Demo script showing the new branch source selection feature

echo "=========================================="
echo "Branch Source Selection Feature Demo"
echo "=========================================="
echo ""

echo "When creating a new session, you'll now see 3 strategy options:"
echo ""
echo "  Branch creation strategy:"
echo "  1. From current state (stay on current branch)"
echo "  2. From default branch (checkout main/master first)"
echo "  3. From specific branch (select and pull)       <-- NEW!"
echo "  Select [2]:"
echo ""

echo "=========================================="
echo "Example 1: Creating from develop branch"
echo "=========================================="
echo ""
echo "User input: 3"
echo ""
echo "Fetching latest from origin..."
echo ""
echo "Available branches:"
echo "1. develop"
echo "2. feature/authentication"
echo "3. main (current)"
echo "4. release/2.5"
echo ""
echo "Select source branch [1]: 1"
echo ""
echo "Checking out develop..."
echo "Pulling latest develop..."
echo "Creating branch: aap-12345-my-feature..."
echo "✓ Created and switched to branch: aap-12345-my-feature"
echo ""

echo "=========================================="
echo "Example 2: Uncommitted changes detected"
echo "=========================================="
echo ""
echo "User input: 3"
echo ""
echo "✗ Error: Cannot switch branches with uncommitted changes"
echo ""
echo "Uncommitted changes:"
echo "  M devflow/git/utils.py"
echo "  ?? new_file.txt"
echo ""
echo "Please commit, stash, or discard your changes before creating a branch from a specific source."
echo "Options:"
echo "  - Commit: git commit -am \"Your message\""
echo "  - Stash: git stash"
echo "  - Discard: git reset --hard HEAD"
echo ""

echo "=========================================="
echo "Key Features:"
echo "=========================================="
echo ""
echo "✓ Select any local branch as source"
echo "✓ Automatically fetches and pulls latest changes"
echo "✓ Safety check: aborts if uncommitted changes exist"
echo "✓ Works with develop, release, and feature branches"
echo "✓ Fully backward compatible with existing workflows"
echo ""

echo "=========================================="
echo "Common Use Cases:"
echo "=========================================="
echo ""
echo "1. Creating feature from develop branch:"
echo "   - Select strategy 3"
echo "   - Choose 'develop' from branch list"
echo "   - New feature branch based on latest develop"
echo ""
echo "2. Creating hotfix from release branch:"
echo "   - Select strategy 3"
echo "   - Choose 'release/2.5' from branch list"
echo "   - New hotfix branch based on release"
echo ""
echo "3. Creating experiment from feature branch:"
echo "   - Select strategy 3"
echo "   - Choose existing feature branch"
echo "   - New experiment branch with feature code"
echo ""

echo "=========================================="
echo "End of Demo"
echo "=========================================="
